${Ipath} =

ngx_list_test: ngx_list_test.o
	gcc -o ngx_list_test ngx_list_test.c -I ../src/core/ -I ../objs/  -I ../src/os/unix/ -I ../pcre-8.41/ -I ../src/event/ ../objs/src/core/ngx_list.o ../objs/src/core/ngx_string.o ../objs/src/core/ngx_palloc.o ../objs/src/os/unix/ngx_alloc.o


# gcc -o ngx_list_test ngx_list_test.c -I ../src/core/ -I ../objs/  -I ../src/os/unix/ -I ../pcre-8.41/ -I ../src/event/ ../objs/src/core/ngx_list.o ../objs/src/core/ngx_string.o ../objs/src/core/ngx_palloc.o ../objs/src/os/unix/ngx_alloc.o